### ISSUE TITLE
Better cryptography

### ISSUE THREAD

**Issue by ziima** [ziima/python-openid#9]
Using custom made cryptography tools is a dangerous as we are not able to keep them secure.

We should use https://cryptography.io/ instead of `cryptutil` and other modules and perform other updates.

### Tasks ###
 * [x] Replace `cryptutil.randomString` and `cryptutil.getBytes` #7 
 * [x] Replace `cryptutil.const_eq` #10
 * [ ] Replace `long` to base64/binary conversions? #11 (partially)
 * [x] Replace hash functions in `cryptutil` #16 
 * [x] Replace HMAC functions in `cryptutil` #17
 * [x] Refactor `dh` module #12
 * [x] Prefer strong association methods #8 
 * [ ] Provide new, stronger authentication methods?
 * [ ] Deprecate SHA1
